-- ════════════════════════════════════════════════════════════════════════════
-- Staff ID on profiles
--
-- WHY
-- Employees and Accountants carry an employee_id (SACS-###); Super Admin,
-- Admin and HR accounts carried no ID at all. They now get their own
-- STAFF-### series, generated by src/lib/employees/staff-id.js when the Super
-- Admin creates the account (POST /api/admin/staff-accounts).
--
-- A separate column, not employee_id: RFID taps, attendance and payroll match
-- people on employee_id, and a staff login is none of those.
--
-- Idempotent: safe to re-run.
-- ════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS staff_id TEXT;

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_staff_id_format;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_staff_id_format
  CHECK (staff_id IS NULL OR staff_id ~ '^STAFF-[0-9]{3,}$');

-- Two Super Admins creating accounts at once can compute the same next ID;
-- this is the real guard (the create route retries on a collision).
CREATE UNIQUE INDEX IF NOT EXISTS profiles_staff_id_unique
  ON public.profiles (staff_id)
  WHERE staff_id IS NOT NULL;

-- Backfill: every existing staff account without one, numbered after the
-- highest ID already issued, oldest account first.
WITH base AS (
  SELECT COALESCE(MAX(substring(staff_id FROM 7)::int), 0) AS max_no
  FROM public.profiles
  WHERE staff_id ~ '^STAFF-[0-9]+$'
),
pending AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC, id ASC) AS rn
  FROM public.profiles
  WHERE staff_id IS NULL
    AND role IN ('super_admin', 'admin', 'hr')
)
UPDATE public.profiles p
SET staff_id = 'STAFF-' || lpad((base.max_no + pending.rn)::text, 3, '0')
FROM pending, base
WHERE p.id = pending.id;
