/**
 * Holidays (public.attendance_holidays): the days besides Saturday and Sunday
 * on which nobody is marked Absent, Late or Incomplete.
 *
 *   type "holiday"     regular holiday (regular_holiday_premium_pct when worked)
 *   type "special"     special non-working day (special_holiday_premium_pct)
 *   type "suspension"  class / work suspension (typhoon, LGU-declared): no
 *                      premium for working it. day_part "whole" is a day
 *                      off; "am" / "pm" with a cutoff time stays a working
 *                      day on a shorter schedule (pm: work ends at the
 *                      cutoff; am: work starts at the cutoff).
 *
 * The nightly close, the status engine (a no-tap day reads "Holiday") and
 * payroll read this table. Super Admin keeps it up to date (System
 * Configuration -> Holidays, /api/admin/holidays); HR may add suspensions.
 * Each year's fixed and computed holidays are generated by
 * public.attendance_seed_holidays (every December 1, and on demand).
 */

export const HOLIDAY_TYPES = Object.freeze(["holiday", "special", "suspension"]);
export const DAY_PARTS = Object.freeze(["whole", "am", "pm"]);
export const HOLIDAY_NAME_MAX = 100;

export const HOLIDAY_TYPE_LABELS = Object.freeze({
  holiday: "Regular Holiday",
  special: "Special Non-Working Day",
  suspension: "Suspension",
});

const DATE_KEY = /^\d{4}-\d{2}-\d{2}$/;
const HHMM = /^([01]\d|2[0-3]):([0-5]\d)$/;

/** A real calendar date in "YYYY-MM-DD" form. */
export function isValidDateKey(value) {
  const key = String(value || "");
  if (!DATE_KEY.test(key)) return false;
  const date = new Date(`${key}T00:00:00Z`);
  return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === key;
}

/** "13:00" or "13:00:00" -> minutes after midnight, or null. */
export function cutoffMinutes(value) {
  const match = HHMM.exec(String(value || "").slice(0, 5));
  return match ? Number(match[1]) * 60 + Number(match[2]) : null;
}

/** Validation for a new holiday. Returns an error message, or null. */
export function validateHolidayInput({ holiday_date: date, name, type, day_part: dayPart = "whole", cutoff } = {}) {
  if (!isValidDateKey(date)) return "Choose the holiday's date.";
  const label = String(name ?? "").trim();
  if (!label) return "Enter the holiday's name.";
  if (label.length > HOLIDAY_NAME_MAX) return `The name can be at most ${HOLIDAY_NAME_MAX} characters.`;
  if (!HOLIDAY_TYPES.includes(String(type || ""))) return "Choose Regular Holiday, Special Non-Working Day or Suspension.";
  const part = String(dayPart || "whole");
  if (!DAY_PARTS.includes(part)) return "Choose whole day, morning or afternoon.";
  if (part !== "whole") {
    if (type !== "suspension") return "Only a suspension can be for the morning or afternoon only.";
    if (cutoffMinutes(cutoff) === null) {
      return part === "pm" ? "Enter the time work is suspended from (HH:MM)." : "Enter the time work resumes (HH:MM).";
    }
  }
  return null;
}

/** "Afternoon suspension from 1:00 PM" / "Morning suspension until 1:00 PM" / "" for a whole day. */
export function describeDayPart(row) {
  const part = String(row?.day_part || "whole");
  if (part === "whole") return "";
  const minutes = cutoffMinutes(row?.cutoff);
  if (minutes === null) return part === "pm" ? "Afternoon only" : "Morning only";
  const h = Math.floor(minutes / 60);
  const m = String(minutes % 60).padStart(2, "0");
  const time = `${h % 12 || 12}:${m} ${h < 12 ? "AM" : "PM"}`;
  return part === "pm" ? `Work suspended from ${time}` : `Work resumes at ${time}`;
}

/**
 * Holidays between two date keys: Map of date key ->
 * { name, type, day_part, cutoff }. null when the table cannot be read, so a
 * caller can tell "no holidays" from "unknown".
 */
export async function readHolidayMap(supabase, startKey, endKey) {
  try {
    const result = await supabase
      .from("attendance_holidays")
      .select("holiday_date,name,type,day_part,cutoff")
      .gte("holiday_date", startKey)
      .lte("holiday_date", endKey);
    if (result.error) return null;
    return new Map((result.data || []).map((row) => [
      String(row.holiday_date).slice(0, 10),
      {
        name: String(row.name || "Holiday"),
        type: HOLIDAY_TYPES.includes(row.type) ? row.type : "holiday",
        day_part: DAY_PARTS.includes(row.day_part) ? row.day_part : "whole",
        cutoff: row.cutoff ? String(row.cutoff).slice(0, 5) : null,
      },
    ]));
  } catch {
    return null;
  }
}

/** True for a day nobody is expected to work: any whole-day holiday or suspension. */
export function isDayOff(holiday) {
  return Boolean(holiday) && (holiday.day_part || "whole") === "whole";
}
